
package com.example.springclient.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentService", targetNamespace = "http://service.demospringservice.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentService {


    /**
     * 
     * @return
     *     returns java.util.List<com.example.springclient.service.Student>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getList", targetNamespace = "http://service.demospringservice.example.com/", className = "com.example.springclient.service.GetList")
    @ResponseWrapper(localName = "getListResponse", targetNamespace = "http://service.demospringservice.example.com/", className = "com.example.springclient.service.GetListResponse")
    @Action(input = "http://service.demospringservice.example.com/StudentService/getListRequest", output = "http://service.demospringservice.example.com/StudentService/getListResponse")
    public List<Student> getList();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveStudent", targetNamespace = "http://service.demospringservice.example.com/", className = "com.example.springclient.service.SaveStudent")
    @ResponseWrapper(localName = "saveStudentResponse", targetNamespace = "http://service.demospringservice.example.com/", className = "com.example.springclient.service.SaveStudentResponse")
    @Action(input = "http://service.demospringservice.example.com/StudentService/saveStudentRequest", output = "http://service.demospringservice.example.com/StudentService/saveStudentResponse")
    public boolean saveStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        Student arg0);

}
